ifndef CONTIKI
  $(error CONTIKI not defined! You must specify where CONTIKI resides!)
endif
PLATFORM_DIR = $(CONTIKI)/platform/mulle
CONTIKI_TARGET_DIRS = .
CONTIKI_CORE=contiki-main
CONTIKI_TARGET_MAIN = ${CONTIKI_CORE}.o

CONTIKI_TARGET_SOURCEFILES += contiki-main.c

include $(PLATFORM_DIR)/mk60/Makefile.mk60
contiki-$(TARGET).a: ${addprefix $(OBJECTDIR)/,symbols.o}


SERIALDUMP = $(CONTIKI)/tools/sky/serialdump-linux

login:
	$(SERIALDUMP) -b115200 $(PORT)
